# Generated by Django 2.2.4 on 2019-08-30 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes', '0003_evento_ubicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='ubicacion',
            new_name='Lugar',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_termino',
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion_general',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='editor',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='hashtag',
            field=models.CharField(default='#hashtag', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='plantilla',
            field=models.CharField(default='plantilla nice', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
