# Generated by Django 2.2.4 on 2019-08-30 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes', '0004_auto_20190830_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Lugar',
            new_name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='descripcion_general',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='plantilla',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_termino',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
