# Generated by Django 2.2.4 on 2019-08-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes', '0006_auto_20190830_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='hashtag',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
