# Generated by Django 2.2.4 on 2019-08-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes', '0007_auto_20190830_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistente',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='asistente',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='asistente',
            unique_together={('evento', 'nombre', 'id')},
        ),
    ]
