# Generated by Django 2.2.4 on 2019-08-30 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes', '0008_auto_20190830_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistente',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='asistente',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=1000)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas', to='asistentes.Evento')),
            ],
        ),
    ]
