# Generated by Django 2.2.4 on 2019-08-30 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes', '0009_auto_20190830_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intinerario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('hora', models.TimeField()),
                ('zona', models.CharField(max_length=100)),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='asistentes.Fecha')),
            ],
        ),
    ]
